name: AWS CodeBuild with Architecture Selection

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64, x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: ${{ steps.codebuild-project-name.outputs.project }}
        buildspec-override: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Running build on ${{ matrix.architecture }}"
                - uname -a

    - name: Get CodeBuild project name
      id: Lambda
      run: |
        PROJECT_NAME=$(aws codebuild list-projects --output text --query "projects[?tags.Architecture=='${{ matrix.architecture }}']")
        echo "project=$PROJECT_NAME" >> $GITHUB_OUTPUT
