name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-Lambda-${{ github.run_id }}-${{ github.run_attempt }}
      - image:590183761178.dkr.ecr.ap-southeast-1.amazonaws.com/myubuntu:25.04
      - instance-size:${{ matrix.size }}
      - buildspec-override:true
    strategy:
      matrix:
        include:
          - os: arm-3.0
            size: small
    steps:
      - run: echo "Hello World"
